version: '2'

services:

  php-fpm:
    build: .docker/php-fpm
    volumes:
     - ./:/var/www/symfony-test
    networks:
      - backend
    links:
      - postgres
      - node

  nginx:
    build: .docker/nginx
    volumes:
      - ./:/var/www/symfony-test
    networks:
      - backend
    ports:
      - "8888:80"
    links:
      - php-fpm

  postgres:
      image: postgres:10.1
      restart: always
      environment:
        - POSTGRES_DB=books
        - POSTGRES_USER=schoolboy
        - POSTGRES_PASSWORD=very_secure
      ports:
        - 5432:5432
      networks:
        - backend

  node:
    build: .docker/node
    volumes:
      - ./:/var/ww/symfony-test
    networks:
      - backend
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      DATABASE_URL: jdbc:postgresql://0.0.0.0:5432/postgres

networks:
  backend: